version: "3"
services:
  bff: # サービス名
    build: # ビルドに使うDockerファイルのパス
      context: .
      dockerfile: ./docker/local/Dockerfile
    tty: true # コンテナの永続化
    environment:
      GRPC_ENDPOINT: ${GRPC_ENDPOINT}
    ports:
      - 4040:4000
    volumes:
      - ./:/go/src/app # マウントディレクトリ
