// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type TodoItem struct {
	ID          string `json:"id"`
	Task        string `json:"task"`
	IsCompleted bool   `json:"is_completed"`
}

type TodoList struct {
	Items []*TodoItem `json:"items"`
}
